# Generated by Django 6.0.1 on 2026-02-26 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('imagen', models.ImageField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recomendado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('masajes', models.TextField()),
                ('servicios', models.TextField()),
                ('horario_atencion', models.TextField()),
                ('idiomas', models.TextField()),
                ('imagen', models.ImageField(upload_to='staff/')),
                ('activo', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
