# Generated by Django 6.0.1 on 2026-02-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='acompanamiento_terapeutico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='para_aprender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
